# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('geojson', models.CharField(max_length=256)),
                ('layer', models.CharField(max_length=256)),
            ],
        ),
    ]
